# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180111_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='top_name',
        ),
    ]
