# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0002_portfolio_portfoliocompanies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliocompanies',
            old_name='portolio_id',
            new_name='portfolio_id',
        ),
    ]
