# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('gics_sector', models.CharField(max_length=200)),
                ('gics_industry', models.CharField(max_length=200)),
                ('gics_industry_group', models.CharField(max_length=200)),
                ('gics_sub_industry_group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closing_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.Company')),
            ],
        ),
    ]
